# Generated by Django 4.2.3 on 2023-07-31 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_contents', models.CharField(max_length=45)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
